### PR TITLE
Update 1.2 release date

### PR DESCRIPTION
**Pull request by oneumyvakin**

### CODE REVIEW

**Comment by vkdnl** [comment]
Since beginning april we receive emails "bad" domain emails
"VirusTotal.com reports "bad" domain ...."
So propably since v1.2 was released.

When we check the VirusTotal website, then we see no current problems on the reported "bad" domains.

We do see that on the reported sites, that there was a problem a long time ago which was also solved a long time ago.
E.g. a report frm 2014 on a site:
Latest URLs hosted in this domain detected by at least one URL scanner or malicious URL dataset. 
1/61 2014-12-25 21:18:29
So it looks that the extension keeps reporting sites as bad when there was in the past once a problem.
Why do we see this problem?

**Comment by oneumyvakin** [comment]
Hi @vkdnl, I've submitted this as bug #18 I think we will skip detected items which are older than 7 days.

**Comment by vkdnl** [comment]
Hello oneumyvakin,
Yes this might be a good solution.
But is there no indication in the virustotal.com API that the current status of the domain is "good" or "bad"?
How was this handled in the previous version of the extention?
Because we see problem since the new version is running.
In the previous version we did no had this "bad" reports

**Comment by oneumyvakin** [comment]
@vkdnl Yes, VirusTotal has not such indication. Because of API limitations extension sends scan request only for home page of domain and if report of home page is "good", than domain recognized as "good".
Since 1.2 extension performs additional request for domain information and checks for "detected_urls", "detected_communicating_samples" and "detected_referrer_samples".

**Pull request merged**
